<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme-rtl.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme-rtl.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme-rtl.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme-rtl.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\css\theme.min.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\apple-store.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\category\icon1.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\category\icon2.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\category\icon3.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\category\icon4.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\category\shape.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\cta\cta-shape.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\cta\mail.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\cta\send.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\cta\shape-bg1.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\cta\shape-bg2.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\dest\dest1.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\dest\dest2.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\dest\dest3.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\dest\navigation.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\dest\shape.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\android-chrome-192x192.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\android-chrome-512x512.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\apple-touch-icon.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\browserconfig.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\favicon-16x16.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\favicon-32x32.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\manifest.json" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\mstile-150x150.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\favicons\site.webmanifest" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\hero\hero-bg.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\hero\hero-img.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\hero\play.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\hero\shape.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\icons\down.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\icons\up.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\logo.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\logo2.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\partner\1.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\partner\2.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\partner\3.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\partner\4.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\partner\5.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\play-store.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\bg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\booking-img.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\building.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\favorite-placeholder.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\heart.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\leaf.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\map.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\selection.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\send.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\taxi.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\steps\water-sport.svg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\testimonial\author.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\testimonial\author2.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\img\testimonial\author3.png" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\js\bootstrap-navbar.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\js\theme.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\js\theme.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\js\theme.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\js\theme.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\video\.gitkeep" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\video\beach.jpg" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\video\beach.mp4" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\assets\video\beach.webm" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\index.html" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\vendors\@popperjs\popper.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\vendors\bootstrap\bootstrap.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\vendors\bootstrap\bootstrap.min.js.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\vendors\fontawesome\all.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\public\vendors\is\is.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\.babelrc" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\.eslintrc" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\.gitignore" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\.prettierignore" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\build.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\clean.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\gulp.json" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\pug.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\script.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\style.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\utils.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\vendor.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\w3c.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulp\watch.gulp.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\gulpfile.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\package-lock.json" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\package.json" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\README.md" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\js\bootstrap-navbar.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\js\detector.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\js\scroll-to-top.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\js\theme.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\js\utils.js" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\index.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\layouts\Layout.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\layouts\LayoutTheme.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\common\DestinationCard.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\common\Footer.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\common\ServiceCard.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\core\Background.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\core\Functions.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\core\Section.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\core\ThemeStyle.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Booking.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Cta.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Destination.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\HeroHeader.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Partner.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Service.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\home\landing\Testimonial.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\navbars\NavbarJadoo.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\sectionTitle\SectionTitle.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\pug\mixins\Variables.pug" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme.css.map" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\.gitkeep" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_background.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_borders.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_colored-links.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_flex.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_position.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_shadow.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\helpers\_text.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_badge.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_browser-support.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_button.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_card.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_form.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_functions.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_helpers.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_heroHeader.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_hover.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_icon.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_mixed.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_mixins.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_nav-tab.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_reboot.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_testimonial.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_theme.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_topnav.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_utilities.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\theme\_variables.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\_bootstrap.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\_user-variables.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\src\scss\_user.scss" />
      <_ContentIncludedByDefault Remove="wwwroot\jadoo\vendors.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\Shared\Components\" />
    </ItemGroup>

</Project>
